"""initdb

Revision ID: 467e5ab9ff2e
Revises: 
Create Date: 2018-08-07 16:33:12.224717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467e5ab9ff2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HS300s',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('security', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('security', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('security')
    )
    op.create_table('stock_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stock', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('price_change', sa.Float(), nullable=True),
    sa.Column('p_change', sa.Float(), nullable=True),
    sa.Column('ma5', sa.Float(), nullable=True),
    sa.Column('ma10', sa.Float(), nullable=True),
    sa.Column('ma20', sa.Float(), nullable=True),
    sa.Column('v_ma5', sa.Float(), nullable=True),
    sa.Column('v_ma10', sa.Float(), nullable=True),
    sa.Column('v_ma20', sa.Float(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock'], ['stock.security'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_history')
    op.drop_table('stock')
    op.drop_table('HS300s')
    # ### end Alembic commands ###
